services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env     
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/nest_db?schema=public
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nest_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: